-- 00_create_catalog_schema.sql
-- Create database (catalog) and schemas for Bronze/Silver/Gold
CREATE OR REPLACE DATABASE RETAIL_CATALOG;
USE DATABASE RETAIL_CATALOG;

CREATE OR REPLACE SCHEMA IF NOT EXISTS BRONZE;
CREATE OR REPLACE SCHEMA IF NOT EXISTS SILVER;
CREATE OR REPLACE SCHEMA IF NOT EXISTS GOLD;