-- 02_silver_layer.sql
-- SILVER LAYER (Cleansed and Enriched Data)
USE DATABASE RETAIL_CATALOG;

CREATE OR REPLACE SCHEMA SILVER;

-- Clean customers
CREATE OR REPLACE VIEW SILVER.CUSTOMERS_CLEAN AS
SELECT
    CUSTOMER_ID,
    INITCAP(TRIM(FIRST_NAME)) AS FIRST_NAME,
    INITCAP(TRIM(LAST_NAME)) AS LAST_NAME,
    LOWER(EMAIL) AS EMAIL,
    COALESCE(PHONE, 'UNKNOWN') AS PHONE,
    INITCAP(CITY) AS CITY,
    INITCAP(STATE) AS STATE,
    SIGNUP_DATE
FROM BRONZE.CUSTOMERS_RAW
WHERE EMAIL IS NOT NULL;

-- Clean products
CREATE OR REPLACE VIEW SILVER.PRODUCTS_CLEAN AS
SELECT
    PRODUCT_ID,
    TRIM(PRODUCT_NAME) AS PRODUCT_NAME,
    TRIM(CATEGORY) AS CATEGORY,
    TRIM(SUB_CATEGORY) AS SUB_CATEGORY,
    PRICE
FROM BRONZE.PRODUCTS_RAW
WHERE PRICE > 0;

-- Clean orders and enrich with customer city/state
CREATE OR REPLACE VIEW SILVER.ORDERS_ENRICHED AS
SELECT
    O.ORDER_ID,
    O.CUSTOMER_ID,
    O.PRODUCT_ID,
    O.QUANTITY,
    O.ORDER_AMOUNT,
    O.ORDER_DATE,
    O.REGION,
    C.CITY AS CUSTOMER_CITY,
    C.STATE AS CUSTOMER_STATE
FROM BRONZE.ORDERS_RAW O
JOIN SILVER.CUSTOMERS_CLEAN C ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE O.ORDER_AMOUNT > 0;

-- Clean returns data
CREATE OR REPLACE VIEW SILVER.RETURNS_CLEAN AS
SELECT
    R.RETURN_ID,
    R.ORDER_ID,
    R.RETURN_REASON,
    R.RETURN_DATE,
    DATEDIFF('day', O.ORDER_DATE, R.RETURN_DATE) AS DAYS_TO_RETURN
FROM BRONZE.RETURNS_RAW R
JOIN BRONZE.ORDERS_RAW O ON R.ORDER_ID = O.ORDER_ID;