-- 03_gold_layer.sql
-- GOLD LAYER (Aggregated Business Logic)
USE DATABASE RETAIL_CATALOG;

CREATE OR REPLACE SCHEMA GOLD;

-- Sales Summary by Category & Region
CREATE OR REPLACE VIEW GOLD.SALES_SUMMARY AS
SELECT
    P.CATEGORY,
    P.SUB_CATEGORY,
    O.REGION,
    SUM(O.ORDER_AMOUNT) AS TOTAL_SALES,
    COUNT(DISTINCT O.CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
    COUNT(DISTINCT O.PRODUCT_ID) AS UNIQUE_PRODUCTS
FROM SILVER.ORDERS_ENRICHED O
JOIN SILVER.PRODUCTS_CLEAN P ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY, P.SUB_CATEGORY, O.REGION;

-- Return Rate Analysis
CREATE OR REPLACE VIEW GOLD.RETURN_RATE_SUMMARY AS
SELECT
    S.CATEGORY,
    S.SUB_CATEGORY,
    S.REGION,
    COUNT(DISTINCT R.ORDER_ID) AS TOTAL_RETURNS,
    COUNT(DISTINCT O.ORDER_ID) AS TOTAL_ORDERS,
    ROUND(COUNT(DISTINCT R.ORDER_ID) / NULLIF(COUNT(DISTINCT O.ORDER_ID), 0) * 100, 2) AS RETURN_RATE
FROM SILVER.ORDERS_ENRICHED O
JOIN SILVER.PRODUCTS_CLEAN S ON O.PRODUCT_ID = S.PRODUCT_ID
LEFT JOIN SILVER.RETURNS_CLEAN R ON O.ORDER_ID = R.ORDER_ID
GROUP BY S.CATEGORY, S.SUB_CATEGORY, S.REGION;

-- Top Performing Cities
CREATE OR REPLACE VIEW GOLD.TOP_CITY_SALES AS
SELECT
    O.CUSTOMER_CITY AS CITY,
    SUM(O.ORDER_AMOUNT) AS TOTAL_SALES,
    COUNT(DISTINCT O.CUSTOMER_ID) AS TOTAL_CUSTOMERS
FROM SILVER.ORDERS_ENRICHED O
GROUP BY O.CUSTOMER_CITY
HAVING SUM(O.ORDER_AMOUNT) > 100000
ORDER BY TOTAL_SALES DESC;

-- Advanced KPI view (CTE)
CREATE OR REPLACE VIEW GOLD.CUSTOMER_KPI_DASHBOARD AS
WITH CITY_SALES AS (
    SELECT CUSTOMER_CITY, SUM(ORDER_AMOUNT) AS TOTAL_SALES
    FROM SILVER.ORDERS_ENRICHED
    GROUP BY CUSTOMER_CITY
),
RETURNS_BY_CITY AS (
    SELECT O.CUSTOMER_CITY, COUNT(R.RETURN_ID) AS TOTAL_RETURNS
    FROM SILVER.ORDERS_ENRICHED O
    LEFT JOIN SILVER.RETURNS_CLEAN R ON O.ORDER_ID = R.ORDER_ID
    GROUP BY O.CUSTOMER_CITY
)
SELECT
    CS.CUSTOMER_CITY,
    CS.TOTAL_SALES,
    RC.TOTAL_RETURNS,
    ROUND(RC.TOTAL_RETURNS / NULLIF(CS.TOTAL_SALES, 0), 4) AS RETURN_TO_SALES_RATIO
FROM CITY_SALES CS
LEFT JOIN RETURNS_BY_CITY RC ON CS.CUSTOMER_CITY = RC.CUSTOMER_CITY
ORDER BY CS.TOTAL_SALES DESC;