-- 04_procedure.sql
-- STORED PROCEDURE (Data Refresh) and audit table
USE DATABASE RETAIL_CATALOG;

CREATE OR REPLACE TABLE GOLD.ETL_AUDIT_LOG (
    RUN_TIMESTAMP TIMESTAMP,
    JOB_NAME STRING,
    STATUS STRING
);

CREATE OR REPLACE PROCEDURE GOLD.SP_REFRESH_GOLD_LAYER()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN
    -- Step 1: Refresh Sales Summary (recreate view)
    EXECUTE IMMEDIATE 'CREATE OR REPLACE VIEW GOLD.SALES_SUMMARY AS
        SELECT P.CATEGORY, P.SUB_CATEGORY, O.REGION,
               SUM(O.ORDER_AMOUNT) AS TOTAL_SALES,
               COUNT(DISTINCT O.CUSTOMER_ID) AS UNIQUE_CUSTOMERS,
               COUNT(DISTINCT O.PRODUCT_ID) AS UNIQUE_PRODUCTS
        FROM SILVER.ORDERS_ENRICHED O
        JOIN SILVER.PRODUCTS_CLEAN P ON O.PRODUCT_ID = P.PRODUCT_ID
        GROUP BY P.CATEGORY, P.SUB_CATEGORY, O.REGION';

    -- Step 2: Log refresh
    INSERT INTO GOLD.ETL_AUDIT_LOG VALUES (CURRENT_TIMESTAMP(), 'SP_REFRESH_GOLD_LAYER', 'SUCCESS');

    RETURN 'Gold layer refreshed successfully';
END;
$$;