-- ==============================================================================
-- 1. BASE TABLES (SOURCES)
--    These tables establish the foundational data structures.
--    Lineage Complexity: EASY (Direct Source)
-- ==============================================================================

-- Table: PRODUCTS (Basic Inventory)
CREATE TABLE PRODUCTS (
    product_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name    VARCHAR2(100) NOT NULL,
    unit_price      NUMBER(10, 2) NOT NULL,
    stock_quantity  NUMBER(10, 0) DEFAULT 0 NOT NULL,
    last_updated_ts TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP
);

-- Table: CUSTOMERS
CREATE TABLE CUSTOMERS (
    customer_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR2(50),
    last_name       VARCHAR2(50),
    email           VARCHAR2(100) UNIQUE,
    registration_dt DATE DEFAULT SYSDATE
);

-- Table: ORDER_HEADERS (The transaction header - tracks total and customer)
CREATE TABLE ORDER_HEADERS (
    order_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id     NUMBER NOT NULL,
    order_date      DATE DEFAULT SYSDATE,
    order_status    VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    total_amount    NUMBER(12, 2) DEFAULT 0 NOT NULL, -- Calculated by trigger/procedure
    CONSTRAINT fk_order_cust FOREIGN KEY (customer_id) REFERENCES CUSTOMERS (customer_id)
);

-- Table: ORDER_ITEMS (The transaction detail - tracks product/price at time of sale)
CREATE TABLE ORDER_ITEMS (
    order_item_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        NUMBER NOT NULL,
    product_id      NUMBER NOT NULL,
    quantity_ordered NUMBER(10, 0) NOT NULL,
    price_at_sale   NUMBER(10, 2) NOT NULL, -- Captures price at time of order
    subtotal_item   NUMBER(10, 2) NOT NULL, -- Calculated: quantity_ordered * price_at_sale (Lineage Source: TRG_ORDER_ITEM_SUBTOTAL_CALC)
    CONSTRAINT fk_item_order FOREIGN KEY (order_id) REFERENCES ORDER_HEADERS (order_id) ON DELETE CASCADE,
    CONSTRAINT fk_item_product FOREIGN KEY (product_id) REFERENCES PRODUCTS (product_id)
);


-- ==============================================================================
-- 2. VIEWS (INTERMEDIATE TRANSFORMATIONS)
--    These define column-level lineage via transformations, joins, and aggregations.
--    Lineage Complexity: MEDIUM (Joins and Simple Aggregation)
-- ==============================================================================

-- View 1: VW_CUSTOMER_ORDERS (Intermediate join for basic order value)
CREATE OR REPLACE VIEW VW_CUSTOMER_ORDERS AS
SELECT
    H.order_id,
    C.customer_id,
    C.email AS customer_email,
    H.order_date,
    H.order_status,
    I.order_item_id,
    I.product_id,
    I.quantity_ordered,
    I.price_at_sale,
    I.subtotal_item
FROM
    ORDER_HEADERS H
JOIN
    CUSTOMERS C ON H.customer_id = C.customer_id
JOIN
    ORDER_ITEMS I ON H.order_id = I.order_id
WHERE
    H.order_status = 'COMPLETED';
    
-- View 2: VW_PRODUCT_SALES_SUMMARY (CTE usage and aggregation for high-level reporting)
-- Lineage Complexity: HIGH (Multiple CTEs, Aggregation, and Derived Columns)
CREATE OR REPLACE VIEW VW_PRODUCT_SALES_SUMMARY AS
WITH RecentOrders AS (
    -- CTE 1: Filter for orders in the last 90 days and get item details
    SELECT
        product_id,
        quantity_ordered,
        subtotal_item
    FROM
        ORDER_ITEMS OI
    JOIN
        ORDER_HEADERS OH ON OI.order_id = OH.order_id
    WHERE
        OH.order_date >= TRUNC(SYSDATE) - 90
),
ProductPerformance AS (
    -- CTE 2: Calculate total sales and revenue from CTE 1
    SELECT
        product_id,
        SUM(quantity_ordered) AS total_units_sold_90d,
        SUM(subtotal_item) AS total_revenue_90d
    FROM
        RecentOrders
    GROUP BY
        product_id
)
SELECT
    P.product_name,
    P.unit_price,
    PP.total_units_sold_90d,
    PP.total_revenue_90d,
    -- Derived lineage: avg_sale_price_90d comes from a calculation involving two aggregated columns
    ROUND(PP.total_revenue_90d / PP.total_units_sold_90d, 2) AS avg_sale_price_90d
FROM
    PRODUCTS P
JOIN
    ProductPerformance PP ON P.product_id = PP.product_id;


-- ==============================================================================
-- 3. TRIGGERS (AUTOMATED LINEAGE & DML)
--    Triggers handle real-time data calculations, demonstrating DML lineage.
-- ==============================================================================

-- Trigger 1: TRG_ORDER_ITEM_SUBTOTAL_CALC
-- Lineage: Calculates subtotal_item using quantity_ordered and price_at_sale.
CREATE OR REPLACE TRIGGER TRG_ORDER_ITEM_SUBTOTAL_CALC
BEFORE INSERT OR UPDATE OF quantity_ordered, price_at_sale ON ORDER_ITEMS
FOR EACH ROW
BEGIN
    :NEW.subtotal_item := :NEW.quantity_ordered * :NEW.price_at_sale;
END;
/

-- Trigger 2: TRG_ORDER_HEADER_TOTAL_UPDATE
-- Lineage: Updates ORDER_HEADERS.total_amount by aggregating ORDER_ITEMS subtotals.
-- Demonstrates cross-table DML lineage from ORDER_ITEMS to ORDER_HEADERS.
CREATE OR REPLACE TRIGGER TRG_ORDER_HEADER_TOTAL_UPDATE
AFTER INSERT OR UPDATE OR DELETE ON ORDER_ITEMS
FOR EACH ROW
DECLARE
    v_order_id NUMBER;
BEGIN
    -- Determine the order_id affected by the DML operation
    IF INSERTING OR UPDATING THEN
        v_order_id := :NEW.order_id;
    ELSIF DELETING THEN
        v_order_id := :OLD.order_id;
    END IF;

    -- Update the total_amount in the header by recalculating the sum of all items for that order
    UPDATE ORDER_HEADERS
    SET total_amount = (
        SELECT NVL(SUM(subtotal_item), 0)
        FROM ORDER_ITEMS
        WHERE order_id = v_order_id
    )
    WHERE order_id = v_order_id;
END;
/


-- ==============================================================================
-- 4. REPORTING TABLE (DESTINATION SINK)
-- ==============================================================================

-- Table: DAILY_SALES_REPORT (Final denormalized sink for management reporting)
CREATE TABLE DAILY_SALES_REPORT (
    report_date     DATE PRIMARY KEY,
    total_revenue   NUMBER(15, 2) NOT NULL,
    total_orders    NUMBER(10, 0) NOT NULL,
    top_selling_product_name VARCHAR2(100),
    top_selling_revenue NUMBER(12, 2)
);


-- ==============================================================================
-- 5. STORED PROCEDURE (COMPLEX ETL/BUSINESS LOGIC)
--    Demonstrates lineage across multiple CTEs, joins, and DML operations.
--    Lineage Complexity: VERY HIGH (Source: ORDER_HEADERS, ORDER_ITEMS, PRODUCTS)
--    (Sink: DAILY_SALES_REPORT)
-- ==============================================================================

-- Procedure: PRC_PROCESS_DAILY_SALES
CREATE OR REPLACE PROCEDURE PRC_PROCESS_DAILY_SALES (p_report_date IN DATE)
AS
BEGIN
    -- 1. DELETE DML Operation (Lineage: DAILY_SALES_REPORT -> N/A)
    DELETE FROM DAILY_SALES_REPORT WHERE report_date = TRUNC(p_report_date);

    -- 2. INSERT DML Operation (Lineage: ORDER_HEADERS, ORDER_ITEMS, PRODUCTS -> DAILY_SALES_REPORT)
    INSERT INTO DAILY_SALES_REPORT (
        report_date,
        total_revenue,
        total_orders,
        top_selling_product_name,
        top_selling_revenue
    )
    WITH DailyRevenue AS (
        -- CTE 1: Calculate Total Revenue and Order Count for the specified day
        SELECT
            TRUNC(H.order_date) AS order_day,
            SUM(H.total_amount) AS daily_revenue,
            COUNT(DISTINCT H.order_id) AS daily_orders
        FROM
            ORDER_HEADERS H
        WHERE
            TRUNC(H.order_date) = TRUNC(p_report_date)
        GROUP BY TRUNC(H.order_date)
    ),
    TopProduct AS (
        -- CTE 2: Identify the top selling product by revenue for the day
        SELECT
            P.product_name,
            SUM(I.subtotal_item) AS product_revenue,
            -- Uses an analytic function (ROW_NUMBER)
            ROW_NUMBER() OVER (ORDER BY SUM(I.subtotal_item) DESC) as rn
        FROM
            ORDER_ITEMS I
        JOIN
            ORDER_HEADERS H ON I.order_id = H.order_id
        JOIN
            PRODUCTS P ON I.product_id = P.product_id
        WHERE
            TRUNC(H.order_date) = TRUNC(p_report_date)
        GROUP BY P.product_name
    )
    SELECT
        TR.order_day,
        TR.daily_revenue,
        TR.daily_orders,
        TP.product_name,
        TP.product_revenue
    FROM
        DailyRevenue TR
    LEFT JOIN
        TopProduct TP ON TP.rn = 1;

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        -- Log or raise an application error
        RAISE_APPLICATION_ERROR(-20001, 'Error processing daily sales report: ' || SQLERRM);
END;
/